import type { Metadata } from 'next';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from '@/components/ThemeProvider';
import { SidebarProvider } from '@/components/ui/sidebar';
import Navbar from '@/components/Navbar';
import MainSidebar from '@/components/MainSidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <SessionProvider>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SidebarProvider>
                            <MainSidebar />
                            <div className="h-screen flex flex-col w-full">
                                <header className="h-24 sticky top-0 left-0 bg-background">
                                    <Navbar />
                                </header>
                                <main className="grow">{children}</main>
                                <footer className="h-24 flex flex-col justify-end items-center p-5">
                                    <p className="text-center">
                                        © 2024 SWEN-746 Team 2
                                    </p>
                                    <p>
                                        Contact{' '}
                                        <a href="mailto:somecoolperson@rit.edu">
                                            <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm font-semibold">
                                                somecoolperson@rit.edu
                                            </code>{' '}
                                            for any questions
                                        </a>
                                    </p>
                                </footer>
                            </div>
                        </SidebarProvider>
                    </ThemeProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
