name: Docker Image CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sisplusplus:$(date +%s)

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
      token: ${{ secrets.CODECOV_TOKEN }}